kind: Deployment
apiVersion: apps/v1
metadata:
  name: pt-max-station-report-viewer
  namespace: maxstation-dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: pt-max-station-report-viewer
  template:
    metadata:
      labels:
        app: pt-max-station-report-viewer
    spec:
      containers:
        - name: pt-max-station-report-viewer
          image: IMAGE_NAME
          # volumeMounts:
          # - name: azurefileshare
          #   mountPath: /app/AppLogs
          env:
          - name: APP_VERSION
            value: IMAGE_NAME
          - name: URL_REPORT_API
            valueFrom:
              secretKeyRef:
                name: report-url-credentials
                key: url_report_api 
          - name: TZ
            value: "Asia/Bangkok"                 
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP           
      restartPolicy: Always
      imagePullSecrets:      
        - name: pt-max-station-registry-secret
      # volumes:
      #   - name: azurefileshare
      #     azureFile:
      #       secretName: storage-credentials
      #       shareName: api-dev
      #       readOnly: false         